### ISSUE TITLE
Request for Codebase and Further Information on Gazetteer Construction Process

### ISSUE THREAD

**Issue by eshoyuan** [Mckysse/USTC-NELSLIP-SemEval2022Task11-IGNF#3]
Currently, I am engaged in a similar project, focusing on NER . Your work has provided me with a unique perspective and has been instrumental in shaping my understanding of the task at hand. I thoroughly enjoyed reading your paper and found it to be highly informative.

However, I am particularly interested in gaining a deeper understanding of the Gazetteer construction process that you have employed in your project. If possible, could you kindly share the codebase or any similar repositories that you may have used during your research? I am keen to understand how the mapping was executed programmatically.

Additionally, I would greatly appreciate it if you could shed some light on the types of manual adjustments of mapping relationships that you had to perform during the process. Any insights or experiences you could share would be invaluable to my ongoing work.

**Comment by Mckysse** [comment]
Thanks for your focus!
1. The gazetteer is the core of such tasks indeed. Actually the final gazetteer that we constructed during the workshop is legally attribute to the corporation (iFLYTEK) where I interned at that time, so I'm sorry that I cannot open that to you. However, I could share you some codes that describe how we extract and organize the gazetteer from the Wikipedia. I hope it could make some help. Do you mind give me an e-mail account so that I can send this code to you?
2. A very good question. As for the manual adjustments of mapping relationships, you have to focus on the specific task and the specific target. For example, for this SemEval task we have 6 types of labels, but there thousands of labels in the Wikipedia database. So we have to judge which set of wiki labels should be integrated into the 6 official labels. I've went through many classic gazetteers from open sources or asking related authors, to understand how to choose wiki labels for constructing my own gazetteer. Besides, we also construct a dev set by our own, through extracting and clozing the template, and adjust our mapping relationships by evaluate the base NER models' performance on our own dev set as well as on the official dev set.

Best,
Chen

**Comment by eshoyuan** [comment]
Thanks for your response and willingness to share the extraction code. I understand the restrictions around the gazetteer. Your insights on manual adjustments are appreciated.

Please send the code to my email: [eshoyuan@gmail.com](mailto:eshoyuan@gmail.com).

**Comment by Mckysse** [comment]
Sent. Please check.

**Comment by andrew6072** [comment]
Thank you for your response and for sharing insights into your work. I appreciate the clarity in your explanation. The extraction code you provided will be immensely helpful for my project.
